SERVER_PORT = 6123
SERVER_BIND = "0.0.0.0"

NODES_ENDPOINT = "/nodes.json"
ZWAVE_ENDPOINT = "/zwave.json"
STATES_ENDPOINT = "/states.json"

SUPPORTED_CUSTOM_ENDPOINTS = [
    ZWAVE_ENDPOINT,
    STATES_ENDPOINT,
    NODES_ENDPOINT
]