SERVER_PORT = 6123
SERVER_BIND = "0.0.0.0"

DOMAIN_ZWAVE = "zwave"
DOMAIN_OZW = "ozw"
SUPPORTED_DOMAINS = [DOMAIN_ZWAVE, DOMAIN_OZW]

NODES_ENDPOINT = "/nodes.json"

SUPPORTED_CUSTOM_ENDPOINTS = [
    NODES_ENDPOINT
]